# autogenerated by species-treetop-gen-nl.rb on 2020-03-23
module FoodFishParser
  module Flat
    module FishNameNL
      REGEX_AREA = /pacifische|noorse|japanse|indische|ijsselmeer|groenlandse|atlantische|argentijnse|alaska/i
      REGEX_ATTR = /zwarte|zwart|witte|witpoot|wit|roze|rood|rode|rivier|pijl|kleine|klein|grote|groot|groene|groen|grise|doorn|coho|chum|blonde|blond|blauwe|blauw/i
      REGEX_NAME = /zwaardvis|zonnevis|zeewolf|zeesnoek|zeekreeft|zeeforel|zeebaars|zalm|wijting|weekdieren|weekdier|vliegende\ vis|vis|vintonijn|vin\ tonijn|tonijn\ albacore|tonijn|tong|tilapia|thon\ albacore|tarbot|tapijtschelp|surimi|st\.\ pierre|sprot|spie|snotolf|snoekbaars|snoek|snapper|sliptong|skrei|skipjack\ tuna|skipjack\ tonijn|seabob\ garnalen|schol|schelvis|schelpen|schelp|schar|sardines|sardinen|sardinelle|sardine|sardienen|sardien|saibling|rouget|rogvleugel|riddervis|regenboogforel|red\ snapper|red\ grouper|raat|poon|pollock|pollak|pilchard|pieterman|pangasius|paling|pagre|oogtonijn|nijlbaars|neustong|mul|mosselen|mossel|meerval|marlijn|mantelschelp|makreel|mahi\-mahi|mahi\ mahi|maatjesha|lom|leng|kreeft|koolvis|kokkel|king\ clip|karper|kabeljauw|inktvis|hondstong|hoki|heilbot|heekrug|heek|harder\ diklip|hamvis|hake|haai|ha|gruis|grouper|griet|geep|geelvintonijn|geelvin\ tonijn|garnalen|garnaal|fint|escolar|dorade|diklipharder|diklip\ harder|daurade|corvina|coquilles|conger\ aal|cocquilles|cobia|claresse|caviaar|braadha|botervis|bot|blood\ snapper|beekridder|barracumundi|barracuda|bacalao|baars|arkschelp|ansovis|ansjovis|alfonsino|albacore\ tonijn|/i
      REGEX_SUFX = /wang|vlees|steur|ringen|ring|moten|kaviaar|filets|filetes|filet|eiwit/i

      REGEX = /
        (?: \b verse \s+ | \b kaviaar \s+ | \b kaviaar \s+ van \s+ | \b gevilde \s+ )?
        \b
        (
          (?: #{REGEX_AREA} \s+ )? (?: #{REGEX_ATTR} \s* )? #{REGEX_NAME} (?: #{REGEX_SUFX} )?
        )
        \b
      /ix
    end
  end
end
