# autogenerated by species-treetop-gen-latin.rb on 2020-04-03
module FoodFishParser
  module Flat
    module FishNameLatin
      REGEX_FIRST = /zygochlamys|zeus|xiphopenaeus|xiphias|trichiurus|trachurus|todarodes|thunnus|theragra|stolephorus|sprattus|sparus|solea|sepiella|sepia|sebastes|scomber|sardinella|sardina|salmo|reinhardtius|psetta|procambarus|portunus|porphyra|pollachius|pleuronectes|pleoticus|placopecten|perna|peraeus|penaeus|penaeidae|pelvetia|pecten|patinopecten|parapenaeopsis|paralomis|paphia|pangasius|pandalus|pagellus|ovalipes|ostrea|oreochromis|orcorhynchus|oncorhynchus|octopus\ vulgaris|nephrops|nemipterus|mytilus|mulinia|micromesistius|metapenaeus|merluccius|merlangius|melanogrammus|macruronus|lophius|loligo|litopenaeus|lithodes|limanda|lethrinus|lepidotrigla|lepidopsetta|lates|katwonus|katwomus|katsuwonus|katsuwomus|illex|homarus|himanthalia|haematococcus|gadus|euthynnus\ \(katsuwonus\)\ pelamis|euthynnus\ \(katsuwonus\)|euthynnus|ensis|engraulis|dunaliella|dosidicus|dicentrarchus|crassostrea|crangon|conger|clupea|clarias|cheilopogon|cerastoderma|cerastoderm|anguilla|anadara|alle\ alle|acipenser/i
      REGEX_SECND = /yessoensis|vulgaris|virens|vannemei|vannamel|vannamei|undulata|umbilicalis|thynnus|tenera|stylifera|sprattus|spp\.|spp|sombrus|solea|solar|scombrus|santolla|salina|salar|ringens|punctatus|productus|pluvialis|platessa|piscatorius|pilchardus|piclhardus|pelatis|pelanis|pelamis|pelagicus|patagonica|pangasius|pacificus|orientalis|officinalis|obesus|novaezelandiae|novaezealandiae|norvegicus|niloticus|nerka|mykiss|mykis|myki\?s|murphyi|muelleri|morhue|morhua|monodon|monoceros|microptera|merluccius|merlangus|merguiensis|maximus|maxima|marinus|magellanicus|macrocephalus|maccoyii|limanda|lepturus|labrax|kroyeri|kisutch|keta|jordani|japonicus|japonica|hyptophthalmus|hypophthalmus|hypophtalmus|hippoglossus|hippoglossoides|hexodon|harengus|gueldenstaedtii|granulosa|gorbusche|gorbuscha|gladius|gigas|gibbosa|gariepinus|galloprovincialis|faber|encrasicolus|elongata|edulis|edule|directus|crangon|conger|clarkii|chilensis|chalcogramma|capensis|cannamel|cannamei|canaliculus|canaliculata|borealis|bogaraveo|bilineata|australis|aurata|atrisignis|argentinus|antiquata|anquilla|anguilla|anchoita|americanus|albacares|alalunga|aeglefinus/i

      REGEX = /
        \b
        (
          #{REGEX_FIRST} (?: \s+ #{REGEX_SECND} )?
        )
        \b
      /ix
    end
  end
end
