# autogenerated by species-treetop-gen-latin.rb on 2020-03-23
module FoodFishParser
  module Flat
    module FishNameLatin
      REGEX_FIRST = /zygochlamys|zeus|xiphopenaeus|xiphias|undaria|ulva|trichiurus|trachurus|todarodes|thunnus|theragra|stolephorus|sprattus|sparus|solea|sepiella|sepia|sebastes|scomber|sardinella|sardina|salmo|saccharina|reinhardtius|psetta|procambarus|portunus|porphyra|pollachius|pleuronectes|pleoticus|placopecten|phymatolithon|perna|penaeus|penaeidae|pelvetia|pecten|patinopecten|parapenaeopsis|paralomis|paphia|pangasius|pandalus|palmaria|pagellus|ovalipes|ostrea|oreochromis|orcorhynchus|oncorhynchus|octopus|nephrops|nemipterus|nelumbo|mytilus|mulinia|micromesistius|metapenaeus|merluccius|merlangius|melanogrammus|macruronus|macrocystis|lophius|loligo|litopenaeus|lithodes|limanda|lethrinus|lepidotrigla|lepidopsetta|lates|laminaria|katwonus|katwomus|katsuwonus|katsuwomus|illex|homarus|himanthalia|haematococcus|gracilaria|gelidium|gadus|fucus|euthynnus|ensis|engraulis|dunaliella|dosidicus|dicentrarchus|crassostrea|crangon|conger|clupea|clarias|chondrus|cheilopogon|cerastoderma|caulerpa|ascophyllum|anguilla|anadara|alle|alaria|acipenser/i
      REGEX_SECND = /yessoensis|vulgaris|virens|vesiculosus|verrucosa|vannamei|undulata|umbilicalis|thynnus|tenera|stylifera|sprattus|spp\.|spp|sombrus|solea|solar|scombrus|santolla|salina|salar|ringens|pyrifera|punctatus|productus|pluvialis|platessa|piscatorius|pinnatifida|pilchardus|pelatis|pelanis|pelamis|pelagicus|patagonica|pangasius|palmata|pacificus|orientalis|officinalis|ocellatus|obesus|nucifera|novaezelandiae|novaezealandiae|norvegicus|nodosum|niloticus|nerka|mykiss|mykis|myki\?s|murphyi|muelleri|morhue|morhua|monodon|monoceros|microptera|merluccius|merlangus|merguiensis|maximus|maxima|marinus|magellanicus|macrocephalus|maccoyii|limanda|lepturus|lentillifera|latissima|lactuca|labrax|kroyeri|kisutch|keta|jordani|japonicus|japonica|hyptophthalmus|hypophtalmus|hippoglossus|hippoglossoides|hexodon|harengus|gueldenstaedtii|granulosa|gorbusche|gorbuscha|gladius|gigas|gibbosa|gariepinus|galloprovincialis|faber|esculenta|encrasicolus|elongata|edulis|edule|directus|digitata|crispus|crangon|conger|clarkii|chilensis|chalcogramma|capensis|cannamei|canaliculus|canaliculata|calcareum|borealis|bogaraveo|bilineata|australis|aurata|atrisignis|argentinus|antiquata|anquilla|anguilla|anchoita|americanus|alle|albacares|alalunga|aeglefinus/i

      REGEX = /
        \b
        (
          #{REGEX_FIRST} (?: \s+ #{REGEX_SECND} )?
        )
        \b
      /ix
    end
  end
end
