# autogenerated by species-treetop-gen-nl.rb on 2020-04-07
module FoodFishParser
  module Flat
    module FishNameNL
      REGEX_AREA = /zeeuwse|tropische|spaanse|peruaanse|patagonische|pacifische|pacific|noorse|noordse|kaapse|japanse|indische|ijsselmeer|groenlandse|filipijnse|europese|engelse|chileense|aziatische|atlantische|argentijnse|antarctische|amerikaanse|alaska|afrikaanse/i
      REGEX_ATTR = /zwarte|zwart|witte|witpoot|wit|roze|rood|rode|rivier|red|platte|plat|pijl|kleine|klein|grote|groot|groene|groen|grise|doorn|coho|chum|chum|chinook|bonte|blonde|blond|blauwe|blauw/i
      REGEX_NAME = /zwemkrab|zwaardvis|zonnevis|zeewolf|zeetong|zeesnoek|zeepaling|zeekreeft|zeekat|zeeforel|zeeduivel|zeebarbeel|zeebaars|zalmforel|zalm|yellowtail\ kingfish|wulk|wijting|wijde\ mantel|weekdieren|weekdier|vongole|vliegende\ vis|vis|vintonijn|vin\ tonijn|victoriabaars|venusschelp|tonijn\ skipjack|tonijn\ albacore|tonijn|tongschar|tong|tilapia|tijgergarnaal|thon\ albacore|tarbot|tapijtschelp|surimi|stokvis|steurgarnaal|steur|steenwijting|steenbolk|staartvis|st\.\ pierre|st\.\ jacobsschelp|sprot|spie|sockeye\ zalm|snotolf|snoekbaars|snoek|snapper|sliptong|skrei|skipjack\ tuna|skipjack\ tonijn|skipjack|sint\-pietervis|sint\ jacobsschelp|senegalese\ tong|seabob\ garnalen|seabob\ garnaal|schol|schelvis|schelpen|schelp|schar|scampi|sardines|sardinen|sardinelle|sardine|sardienen|sardien|salmon|saibling|rouget|rogvleugel|riddervis|reuzengarnaal|regenboogforel|raat|poon|pollock|pollak|pilchard|pijlinktvis|pieterman|papegaaivis|pangasius|panga|paling|pagre|oregon\ garnaal|oogtonijn|omegabaars|ombervis|oester|octopus|noordzeekrab|nijlbaars|neustong|mul|mosselen|mossel|mesheft|merluza|meerval|marlijn|mantelschelp|makreel|mahi\-mahi|mahi\ mahi|maatjesha|lom|leng|lekkerbekje|langoustine|langoest|krill|kreeft|krab|koolvis|koningskrab|koningsgarnaal|kokkel|king\ clip|keizersbaars|karper|kabeljauw|john\ dory|je|inktvis|ijsheek|horsmakreel|hondstong|hondshaai|hoki|heilbot|heekrug|heek|haring|harder\ diklip|harder|hamvis|hake|haai|gruis|grouper|griet|grauwe\ poon|goudstreep\ sardine|goudmakreel|geep|geelvintonijn|geelvin\ tonijn|geelstaart\ koningsvis|garnalen|garnaal|gamba|forel|fint|escolar|dorade|dolfijnvis|diklipharder|diklip\ harder|diepzee\ roodbaars|daurade|corvina|coquilles|coquille|conger\ aal|cocquilles|cobia|claresse|caviaar|braadha|botervis|bot|bonito|blood\ snapper|beluga|beekridder|barracumundi|barracuda|bacalao|baars|arkschelp|ansovis|ansjovis|alikruik|alfonsino|albacore\ tonijn/i
      REGEX_SUFX = /wang|vlees|steur|ringen|ring|moten|lever|kaviaar|filets|filetes|filet|eiwit/i

      REGEX = /
        (?: \b verse \s+ | \b kaviaar \s+ | \b kaviaar \s+ van \s+ | \b gevilde \s+ )?
        \b
        (
          (?: #{REGEX_AREA} \s+ )? (?: #{REGEX_ATTR} \s* )? #{REGEX_NAME} (?: #{REGEX_SUFX} )?
        )
        \b
      /ix
    end
  end
end
