require 'treetop'
require_relative 'nodes'

# @todo find a way to auto-generate Ruby from Treetop files when building gem,
#       see https://stackoverflow.com/q/37794587/2866660

# note that the species name files are autogenerated
Treetop.load File.dirname(__FILE__) + '/grammar/common'
Treetop.load File.dirname(__FILE__) + '/grammar/fish_name_latin'
Treetop.load File.dirname(__FILE__) + '/grammar/fish_name_nl'
Treetop.load File.dirname(__FILE__) + '/grammar/fish_name'
Treetop.load File.dirname(__FILE__) + '/grammar/words'
Treetop.load File.dirname(__FILE__) + '/grammar/fao_area'
Treetop.load File.dirname(__FILE__) + '/grammar/catch_area'
Treetop.load File.dirname(__FILE__) + '/grammar/catch_method'
Treetop.load File.dirname(__FILE__) + '/grammar/aquac_area'
Treetop.load File.dirname(__FILE__) + '/grammar/aquac_method'
Treetop.load File.dirname(__FILE__) + '/grammar/root'
